---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться на сайте
  - Пользователь должен иметь возможность выбора соперника (с любым человеком, ботом или другом)
  - Пользователь должен иметь возможность выбора игры по уровню сложности
  - Пользователь должен иметь возможность видеть решение соперника в реальном времени
  - Пользователь должен иметь возможность менять язык программировния во время решения
  - Пользователь должен иметь возможность выбрать определенную игру (иначе она подбирается наугад)
  - Пользователь должен иметь возможность переключить задачу на русский язык
  - Пользователь должен иметь возможность переключить задачу на английский язык
  - Другие пользователи должны иметь возможность следить за ходом игры
  - Зарегистрированные пользователи должны иметь возможность общаться в чате игры
  - Пользователь должен иметь возможность посмотреть запись завершенной игры
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность установить расширение для браузера Google Chrome
  - Пользователь не должен иметь возможность писать и изменять код соперника
